# Generated by Django 2.2 on 2019-04-03 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Deck', max_length=200)),
                ('public', models.BooleanField(default=True)),
                ('slug', models.CharField(default='oops', max_length=100, unique=True)),
                ('categories', models.ManyToManyField(related_name='deck', to='core.Category')),
                ('kreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deck', to='core.Quiz')),
                ('users', models.ManyToManyField(related_name='deck_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=500)),
                ('correct', models.BooleanField(blank=True, default=False, null=True)),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='core.Deck')),
            ],
        ),
    ]
