# Generated by Django 2.2 on 2019-04-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='core.Deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='core.Deck'),
        ),
    ]
