# Generated by Django 2.2 on 2019-04-04 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190403_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(blank=True, null=True, related_name='card', to='core.Deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='deck_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
