# Generated by Django 2.2 on 2019-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190403_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='kreator',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='users',
        ),
        migrations.AlterField(
            model_name='card',
            name='correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(blank=True, related_name='card', to='core.Deck'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Kreator',
        ),
    ]
