# Generated by Django 2.2 on 2019-04-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190403_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
