# Generated by Django 2.2 on 2019-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190404_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(blank=True, related_name='card', to='core.Deck'),
        ),
    ]
