# Generated by Django 2.2 on 2019-04-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190404_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deck',
            new_name='decks',
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
