# Generated by Django 2.2 on 2019-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190404_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='categories',
            field=models.ManyToManyField(related_name='decks', to='core.Category'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
