# Generated by Django 2.2 on 2019-04-08 11:52

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File
from django.utils.text import slugify
from django.contrib.auth.models import User

def load_cards_data(apps, schema_editor):
    """
    Read a CSV file full of decks and insert them into the database
    """
    Card = apps.get_model('core', 'Card')
    Deck = apps.get_model('core', 'Deck')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'cards.csv')
    Card.objects.all().delete()

    with open(datafile) as file: 
        reader = csv.DictReader(file)
        for row in reader:
            deck_title = row['question']
            if Deck.objects.filter(title=deck_title).count():
                continue

            if not row['decks']:
                decks, _ = Deck.objects.get_or_create(title='No Deck', slug="no-deck")
                decks = [decks]
            else:
                decks = []
                deck_list = [deck.strip() for deck in row['decks'].split('/')]
                for deck in deck_list:
                    new_deck, _ = Deck.objects.get_or_create(title=deck, slug=slugify(deck))
                    decks.append(new_deck)

            card = Card.objects.create(
                question=row['question'],
                answer=row['answer'],
            )

            for deck in decks:
                card.decks.add(deck)

            card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190408_1149'),
    ]

    operations = [
        migrations.RunPython(load_cards_data)
    ]
